// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CellController from "./cell_controller"
application.register("cell", CellController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PasswordVerificationController from "./password_verification_controller.js"
application.register("password-verification", PasswordVerificationController)

import PrevisualizacionController from "./previsualizacion_controller"
application.register("previsualizacion", PrevisualizacionController)
